### ISSUE TITLE
Latte is...

### ISSUE THREAD

**Issue by onwn** [yunjae2/latte#1]
= 라떼는 말이야.

L 라떼는 말이야,
A 어린 놈들 요즘...
T 떼잉,,,
T 쯧쯧
E 에잉,,, 씁!

**Comment by yunjae2** [comment]
Tsut Tsut
온운님의 유머에 웃고 갑니다.. ㅎㅎ

**Comment by onwn** [comment]
Desire for humor resolved, closing this issue.
